disabled_rules:
- file_name
- explicit_acl
- explicit_top_level_acl
- explicit_type_interface
- explicit_enum_raw_value
- no_extension_access_modifier
- attributes # rule is too subjective
- no_grouping_extension # grouping extensions are ok
- vertical_whitespace_between_cases # increases code length without pros
- todo # we love todos
- trailing_whitespace # IDE will handle it for us
- vertical_whitespace_opening_braces # readability improves
- override_in_extension
- private_outlet
- private_action

opt_in_rules:
- array_init
- anyobject_protocol
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discarded_notification_center_observer
- empty_count
- empty_string
- explicit_init
- empty_xctest_method
- fallthrough
- fatal_error_message
- file_name
- file_length
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicit_return
- joined_default_parameter
- last_where
- let_var_whitespace
- legacy_random
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_parameters
- multiline_literal_brackets
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prohibited_super_call
- redundant_nil_coalescing
- redundant_type_annotation
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- toggle_bool
- trailing_closure
- unneeded_parentheses_in_closure_argument
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- xct_specific_matcher
- yoda_condition

large_tuple: 4
function_body_length : 50
function_parameter_count: 5
warning_threshold: 1
closure_body_length: 16
file_length: 750

cyclomatic_complexity:
  warning: 5
  ignores_case_statements: true

line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true

nesting:
  type_level: 3

conditional_returns_on_newline:
  if_only: true

identifier_name:
  max_length: 40
  min_length: 1

statement_position:
  statement_mode: uncuddled_else

file_name:
  prefix_pattern: ""
  suffix_pattern: "Extensions?|\\+.*"

warning_threshold: 1

custom_rules:
  no_break_with_label:
    regex: "[ ]+break [A-z0-9]+"
    message: "Please, don't use break with label"

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
#included: